name: Unit Test Injector

on:
  pull_request:

jobs:
  build-injector:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Install Rust toolchain"
        uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b # master
        with:
          toolchain: stable

      - name: "Build Rust Binary for x86_64 and arm64"
        run: |
          make install-cross
          make unit-test